<?xml version="1.0" encoding="ASCII"?>
<ResourceModel:App xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ResourceModel="http://www.infineon.com/Davex/Resource.ecore" name="ACIM_FREQ_CTRL" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0" description="Supports frequency control- constant V/f Control&#xA;for the AC induction motor (ACIM)." mode="NOTSHARABLE" version="4.0.8" minDaveVersion="4.0.0" instanceLabel="ACIM_FREQ_CTRL_0" appLabel="" containingProxySignal="true">
  <properties provideInit="true"/>
  <virtualSignals name="i_average_channel" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1" hwSignal="gch" hwResource="//@hwResources.0"/>
  <virtualSignals name="i_average_channel_select" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1_sel" hwSignal="select" hwResource="//@hwResources.0"/>
  <virtualSignals name="i_average_result_select" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1_ressel" hwSignal="res_sel" hwResource="//@hwResources.0"/>
  <virtualSignals name="v_dclink_channel" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2" hwSignal="gch" hwResource="//@hwResources.1"/>
  <virtualSignals name="v_dclink_channel_select" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2_sel" hwSignal="select" hwResource="//@hwResources.1"/>
  <virtualSignals name="v_dclink_result_select" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2_ressel" hwSignal="res_sel" hwResource="//@hwResources.1"/>
  <virtualSignals name="analog_input_channel" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3" hwSignal="gch" hwResource="//@hwResources.2"/>
  <virtualSignals name="analog_input_channel_select" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3_sel" hwSignal="select" hwResource="//@hwResources.2"/>
  <virtualSignals name="analog_input_result_select" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3_ressel" hwSignal="res_sel" hwResource="//@hwResources.2"/>
  <virtualSignals name="user_defined_channel" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4" hwSignal="gch" hwResource="//@hwResources.3"/>
  <virtualSignals name="user_defined_channel_select" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4_sel" hwSignal="select" hwResource="//@hwResources.3"/>
  <virtualSignals name="user_defined_result_select" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4_ressel" hwSignal="res_sel" hwResource="//@hwResources.3"/>
  <virtualSignals name="i_average_result" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1_res" hwSignal="res_sel" hwResource="//@hwResources.8"/>
  <virtualSignals name="v_dclink_result" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2_res" hwSignal="res_sel" hwResource="//@hwResources.9"/>
  <virtualSignals name="analog_input_result" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3_res" hwSignal="res_sel" hwResource="//@hwResources.10"/>
  <virtualSignals name="user_defined_result" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4_res" hwSignal="res_sel" hwResource="//@hwResources.11"/>
  <virtualSignals name="i_average_pad" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1_io" hwSignal="pad" hwResource="//@hwResources.4" required="false"/>
  <virtualSignals name="v_dclink_pad" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2_io" hwSignal="pad" hwResource="//@hwResources.5" required="false"/>
  <virtualSignals name="analog_input_pad" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3_io" hwSignal="pad" hwResource="//@hwResources.6" required="false"/>
  <virtualSignals name="user_defined_pad" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4_io" hwSignal="pad" hwResource="//@hwResources.7" required="false"/>
  <virtualSignals name="sr_fast_control_loop" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_fcl_nvicsignal_in" hwSignal="signal_in" hwResource="//@hwResources.12" visible="true"/>
  <virtualSignals name="sr_primary_control_loop" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_pcl_nvicsignal_in" hwSignal="signal_in" hwResource="//@hwResources.13" required="false" visible="true"/>
  <virtualSignals name="I_Average pin_signal" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_vs_acim_freq_ctrl_adcch1_io" hwSignal="pin" hwResource="//@hwResources.14"/>
  <virtualSignals name="V_DCLink pin_signal" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_vs_acim_freq_ctrl_adcch2_io" hwSignal="pin" hwResource="//@hwResources.15"/>
  <virtualSignals name="Analog_Input pin_signal" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_vs_acim_freq_ctrl_adcch3_io" hwSignal="pin" hwResource="//@hwResources.16"/>
  <virtualSignals name="User_Defined pin_signal" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_vs_acim_freq_ctrl_adcch4_io" hwSignal="pin" hwResource="//@hwResources.17"/>
  <requiredApps URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/appres_queue_a" requiredAppName="ADC_QUEUE" required="false"/>
  <requiredApps URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/appres_queue_b" requiredAppName="ADC_QUEUE" required="false"/>
  <requiredApps URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/appres_queue_c" requiredAppName="ADC_QUEUE" required="false"/>
  <requiredApps URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/appres_queue_d" requiredAppName="ADC_QUEUE" required="false"/>
  <requiredApps URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/appres_pwm_svm" requiredAppName="PWM_SVM">
    <downwardMapList xsi:type="ResourceModel:App" href="../../PWM_SVM/v4_0_22/PWM_SVM_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/appres_motor_lib" requiredAppName="MOTOR_LIB" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../MOTOR_LIB/v4_0_8/MOTOR_LIB_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/appres_cpu" requiredAppName="CPU_CTRL_XMC4" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../CPU_CTRL_XMC4/v4_0_14/CPU_CTRL_XMC4_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/appres_automation" requiredAppName="AUTOMATION" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../AUTOMATION/v4_0_10/AUTOMATION_0.app#/"/>
  </requiredApps>
  <hwResources name="I_Average" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/hwres_adcchan1" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="V_DCLink" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/hwres_adcchan2" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Analog_Input" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/hwres_adcchan3" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="User_Defined" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/hwres_adcchan4" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="I_Average pin" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/hwres_chan_a_pin" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="V_DCLink pin" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/hwres_chan_b_pin" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Analog_Input pin" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/hwres_chan_c_pin" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="User_Defined pin" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/hwres_chan_d_pin" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="I_Average Result" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/hwres_result1" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/result/*"/>
  <hwResources name="V_DCLink Result" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/hwres_result2" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/result/*"/>
  <hwResources name="Analog_Input Result" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/hwres_result3" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/result/*"/>
  <hwResources name="User_Defined Result" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/hwres_result4" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/result/*"/>
  <hwResources name="FCL nvic node" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/hwres_fcl_nvicnode" resourceGroupUri="peripheral/cpu/0/nvic/interrupt/*" mResGrpUri="peripheral/cpu/0/nvic/interrupt/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/CPU/CPU_0.dd#//@provided.3"/>
  </hwResources>
  <hwResources name="PCL nvic node" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/hwres_pcl_nvicnode" resourceGroupUri="" required="false" mResGrpUri="peripheral/cpu/0/nvic/interrupt/*"/>
  <hwResources name="I_Average pin" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_hwres_chan_a_pin" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="V_DCLink pin" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_hwres_chan_b_pin" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Analog_Input pin" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_hwres_chan_c_pin" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="User_Defined pin" URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_hwres_chan_d_pin" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_svm_phu_periodmatch/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_fcl_nvicsignal_in" systemDefined="true" sourceSignal="event_ph_u_period/one_match" targetSignal="sr_fast_control_loop" targetVirtualSignal="//@virtualSignals.20" proxySrcVirtualSignalUri="http://resources/4.0.22/app/PWM_SVM/0/vs_pwm_svm_pmus_omds_phu" containingProxySignal="true">
    <downwardMapList xsi:type="ResourceModel:VirtualSignal" href="../../PWM_SVM/v4_0_22/PWM_SVM_0.app#//@virtualSignals.12"/>
    <srcVirtualSignal href="../../PWM_SVM/v4_0_22/PWM_SVM_0.app#//@virtualSignals.12"/>
  </connections>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_svm_phv_periodmatch/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_pcl_nvicsignal_in" systemDefined="true" sourceSignal="event_ph_v_period/one_match" targetSignal="sr_primary_control_loop" required="false" targetVirtualSignal="//@virtualSignals.21" proxySrcVirtualSignalUri="http://resources/4.0.22/app/PWM_SVM/0/vs_pwm_svm_pmus_omds_phv" containingProxySignal="true">
    <srcVirtualSignal href="../../PWM_SVM/v4_0_22/PWM_SVM_0.app#//@virtualSignals.13"/>
  </connections>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1_io/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1" systemDefined="true" sourceSignal="i_average_pad" targetSignal="i_average_channel" required="false" srcVirtualSignal="//@virtualSignals.16" targetVirtualSignal="//@virtualSignals.0"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2_io/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2" systemDefined="true" sourceSignal="v_dclink_pad" targetSignal="v_dclink_channel" required="false" srcVirtualSignal="//@virtualSignals.17" targetVirtualSignal="//@virtualSignals.3"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3_io/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3" systemDefined="true" sourceSignal="analog_input_pad" targetSignal="analog_input_channel" required="false" srcVirtualSignal="//@virtualSignals.18" targetVirtualSignal="//@virtualSignals.6"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4_io/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4" systemDefined="true" sourceSignal="user_defined_pad" targetSignal="user_defined_channel" required="false" srcVirtualSignal="//@virtualSignals.19" targetVirtualSignal="//@virtualSignals.9"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue12channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1_sel" systemDefined="true" sourceSignal="queue_select" targetSignal="i_average_channel_select" required="false" targetVirtualSignal="//@virtualSignals.1" proxySrcVirtualSignalUri="http://resources/4.0.20/app/ADC_QUEUE/0/vs_adc_queue_queue2channel" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue12channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2_sel" systemDefined="true" sourceSignal="queue_select" targetSignal="v_dclink_channel_select" required="false" targetVirtualSignal="//@virtualSignals.4" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue12channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3_sel" systemDefined="true" sourceSignal="queue_select" targetSignal="analog_input_channel_select" required="false" targetVirtualSignal="//@virtualSignals.7" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue12channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4_sel" systemDefined="true" sourceSignal="queue_select" targetSignal="user_defined_channel_select" required="false" targetVirtualSignal="//@virtualSignals.10" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue22channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1_sel" systemDefined="true" targetSignal="i_average_channel_select" required="false" targetVirtualSignal="//@virtualSignals.1" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue22channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2_sel" systemDefined="true" targetSignal="v_dclink_channel_select" required="false" targetVirtualSignal="//@virtualSignals.4" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue22channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3_sel" systemDefined="true" targetSignal="analog_input_channel_select" required="false" targetVirtualSignal="//@virtualSignals.7" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue22channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4_sel" systemDefined="true" targetSignal="user_defined_channel_select" required="false" targetVirtualSignal="//@virtualSignals.10" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue32channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1_sel" systemDefined="true" targetSignal="i_average_channel_select" required="false" targetVirtualSignal="//@virtualSignals.1" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue32channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2_sel" systemDefined="true" targetSignal="v_dclink_channel_select" required="false" targetVirtualSignal="//@virtualSignals.4" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue32channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3_sel" systemDefined="true" targetSignal="analog_input_channel_select" required="false" targetVirtualSignal="//@virtualSignals.7" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue32channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4_sel" systemDefined="true" targetSignal="user_defined_channel_select" required="false" targetVirtualSignal="//@virtualSignals.10" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue42channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1_sel" systemDefined="true" targetSignal="i_average_channel_select" required="false" targetVirtualSignal="//@virtualSignals.1" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue42channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2_sel" systemDefined="true" targetSignal="v_dclink_channel_select" required="false" targetVirtualSignal="//@virtualSignals.4" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue42channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3_sel" systemDefined="true" targetSignal="analog_input_channel_select" required="false" targetVirtualSignal="//@virtualSignals.7" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_adc_queue_queue42channel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4_sel" systemDefined="true" targetSignal="user_defined_channel_select" required="false" targetVirtualSignal="//@virtualSignals.10" containingProxySignal="true"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1_ressel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1_res" systemDefined="true" sourceSignal="i_average_result_select" targetSignal="i_average_result" required="false" srcVirtualSignal="//@virtualSignals.2" targetVirtualSignal="//@virtualSignals.12"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2_ressel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2_res" systemDefined="true" sourceSignal="v_dclink_result_select" targetSignal="v_dclink_result" required="false" srcVirtualSignal="//@virtualSignals.5" targetVirtualSignal="//@virtualSignals.13"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3_ressel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3_res" systemDefined="true" sourceSignal="analog_input_result_select" targetSignal="analog_input_result" required="false" srcVirtualSignal="//@virtualSignals.8" targetVirtualSignal="//@virtualSignals.14"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4_ressel/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4_res" systemDefined="true" sourceSignal="user_defined_result_select" targetSignal="user_defined_result" required="false" srcVirtualSignal="//@virtualSignals.11" targetVirtualSignal="//@virtualSignals.15"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1_io/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_vs_acim_freq_ctrl_adcch1_io" systemDefined="true" sourceSignal="i_average_pad" targetSignal="I_Average pin_signal" srcVirtualSignal="//@virtualSignals.16" targetVirtualSignal="//@virtualSignals.22"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_vs_acim_freq_ctrl_adcch1_io/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch1_io" systemDefined="true" sourceSignal="I_Average pin_signal" targetSignal="i_average_pad" srcVirtualSignal="//@virtualSignals.22" targetVirtualSignal="//@virtualSignals.16"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2_io/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_vs_acim_freq_ctrl_adcch2_io" systemDefined="true" sourceSignal="v_dclink_pad" targetSignal="V_DCLink pin_signal" srcVirtualSignal="//@virtualSignals.17" targetVirtualSignal="//@virtualSignals.23"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_vs_acim_freq_ctrl_adcch2_io/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch2_io" systemDefined="true" sourceSignal="V_DCLink pin_signal" targetSignal="v_dclink_pad" srcVirtualSignal="//@virtualSignals.23" targetVirtualSignal="//@virtualSignals.17"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3_io/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_vs_acim_freq_ctrl_adcch3_io" systemDefined="true" sourceSignal="analog_input_pad" targetSignal="Analog_Input pin_signal" srcVirtualSignal="//@virtualSignals.18" targetVirtualSignal="//@virtualSignals.24"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_vs_acim_freq_ctrl_adcch3_io/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch3_io" systemDefined="true" sourceSignal="Analog_Input pin_signal" targetSignal="analog_input_pad" srcVirtualSignal="//@virtualSignals.24" targetVirtualSignal="//@virtualSignals.18"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4_io/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_vs_acim_freq_ctrl_adcch4_io" systemDefined="true" sourceSignal="user_defined_pad" targetSignal="User_Defined pin_signal" srcVirtualSignal="//@virtualSignals.19" targetVirtualSignal="//@virtualSignals.25"/>
  <connections URI="http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/__pin_vs_acim_freq_ctrl_adcch4_io/http://resources/4.0.8/app/ACIM_FREQ_CTRL/0/vs_acim_freq_ctrl_adcch4_io" systemDefined="true" sourceSignal="User_Defined pin_signal" targetSignal="user_defined_pad" srcVirtualSignal="//@virtualSignals.25" targetVirtualSignal="//@virtualSignals.19"/>
</ResourceModel:App>
